name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      
    - name: Add all files to git
      run: git add -A
      
    - name: Commit changes
      run: |
        git config --local user.email "mees.akveld@student.arteveldehs.be"
        git config --local user.name "pgm-meesakveld"
        git checkout gh-pages
        git commit -m "Deploy to gh-pages"
      
    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
